terminal:
  image: ruby:3.0
  before_script:
    - apt update
    - curl -sL https://deb.nodesource.com/setup_12.x | sudo -E bash -
    - apt install nodejs
    - gem install bundler:2.2.11
  script: sleep 60
  variables:
    NODE_ENV: "development"
  services:
    - name: registry.gitlab.com/gitlab-org/webide-file-sync:latest
      alias: webide-file-sync
      entrypoint: ["/bin/sh"]
      command: ["-c", "sleep 5 && ./webide-file-sync -project-dir $CI_PROJECT_DIR"]
      ports:
        - number: 3000
