title: GNOME UI
email: engagement@gnome.org
description: >-
  GNOME's own UI library.
baseurl: "/Engagement/websites/general-website-resources"
#url: "https://teams.pages.gitlab.gnome.org"
twitter_username: GNOME
logo: "/assets/logo-horizontal.svg"

# Build settings
theme: just-the-docs
color_scheme: gnome-blue

plugins:
  - jekyll-feed


# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
